[package]
name = "grola"
version = "0.1.0"
edition = "2021"
build = "src/make_parser.rs"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tinytemplate = "1.2.1"
toml = "0.8.14"

[build-dependencies]
toml = "0.8.14"
serde = { version = "1.0.203", features = ["derive"] }

#[[bin]]
#name = "parser"
#path = "src/parse.rs"
#
#[[bin]]
#name = "router"
#path = "src/route.rs"
